### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by henokkhm** [RileyManda/scimovies-capstone-project#37]
@RileyManda Awesome work thus far! 

One thing I want to point out is the specific requirements for this feature.

- Each counter should be implemented as a separate module.
- A counter function should look for specific DOM elements (e.g. for the comments counter it should look for comments) and make the counting based on what is actually displayed on the page.

Currently, you're counting the items after you call fetch() and simply getting the **length**. I hope the point I'm making is clear and you can make these adjustments. Feel free to comment if you have any questions.

**Comment by RileyManda** [comment]
Hi @henokkhm :wave:

Thank you for your peer review on my implementation.

I will update my implementation by removing the additional function getTVShowsCount that was fetching data from the server again from getTvShow.js and implement itemsCounter to count the number of items on the dom.
getTvShows will now only focus on fetching items from the server to populate the view while itemsCounter will count the children and pass the parameter as a util to the dom to display the count on children

Thank you for your advice and input on this.:handshake:

Much appreciated.
